data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  aggr: sage
  loss: softmax
  num_layers: 5
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: max
  pooling: max
hyperparameter:
  end: 50
  lr: 1e-4
  dropout: 0.2
  dropedge: 0.15
  batch_size: 128
sampler:
  - method: ppr
    phase: train
    k: [200]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.97160            0.97034                   41
#        0.97160            0.97013                   27
#        0.97211            0.97007                   26
#        0.97143            0.97020                   40
#        0.97181            0.97094                   49
# ------------------------------------------------------
# avg:    0.9717             0.9703
# std:    0.0002             0.0003