data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  aggr: gat
  heads: 4
  loss: sigmoid
  num_layers: 3
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: max
  pooling: max
hyperparameter:
  end: 100
  lr: 0.0005
  dropout: 0.1
  dropedge: 0.0
  batch_size: 16
sampler:
  - method: ppr
    phase: train
    k: [100]
    threshold: [0.001]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.65625            0.65662                   93
#        0.65649            0.65693                   87
#        0.65663            0.65679                   78
#        0.65654            0.65690                   89
#        0.65539            0.65559                   87
# ------------------------------------------------------
# avg:    0.6563             0.6566
# std:    0.0005             0.0005
