data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  aggr: gat
  heads: 4
  loss: sigmoid
  num_layers: 3
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 100
  lr: 0.0005
  dropout: 0.1
  dropedge: 0.0
  batch_size: 16
sampler:
  - method: ppr
    phase: train
    k: [100]
    threshold: [0.001]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.65687            0.65700                   99
#        0.65713            0.65756                   98
#        0.65679            0.65726                   65
#        0.65760            0.65826                   69
#        0.65712            0.65726                   79
# ------------------------------------------------------
# avg:    0.6571             0.6575
# std:    0.0003             0.0004
