data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  aggr: gat
  heads: 4
  loss: sigmoid
  num_layers: 5
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 100
  lr: 0.0005
  dropout: 0.1
  dropedge: 0.0
  batch_size: 16
sampler:
  - method: ppr
    phase: train
    k: [100]
    threshold: [0.001]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.65541            0.65560                   62
#        0.65551            0.65596                   81
#        0.65644            0.65626                   83
#        0.65566            0.65573                   66
#        0.65538            0.65603                   79
# ------------------------------------------------------
# avg:    0.6557             0.6559
# std:    0.0004             0.0002
