data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  aggr: gcn
  loss: sigmoid
  num_layers: 3
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 100
  lr: 0.001
  dropout: 0.1
  dropedge: 0.0
  batch_size: 32
sampler:
  - method: ppr
    phase: train
    k: [100]
    threshold: [0.001]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.52775            0.53010                   70
#        0.52474            0.52695                   65
#        0.53007            0.53224                   94
#        0.52612            0.52893                   93
#        0.52460            0.52711                   67
# ------------------------------------------------------
# avg:    0.5267             0.5291
# std:    0.0021             0.0020
