data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  aggr: sage
  loss: sigmoid
  num_layers: 3
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 100
  lr: 0.0005
  dropout: 0.1
  dropedge: 0.0
  batch_size: 16
sampler:
  - method: ppr
    phase: train
    k: [100]
    threshold: [0.001]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.65305            0.65323                   52
#        0.65354            0.65402                   96
#        0.65363            0.65394                   94
#        0.65375            0.65397                   84
#        0.65330            0.65401                   82
# ------------------------------------------------------
# avg:    0.6535             0.6538
# std:    0.0003             0.0003