data:
  transductive: True
architecture:
  dim: 256
  aggr: gcn
  loss: softmax
  num_layers: 5
  act: relu
  feature_augment: none
  feature_smoothen: none
  use_label: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 35
  lr: 0.002
  dropout: 0.35
  dropedge: 0.05
  batch_size: 128
sampler:
  - method: ppr
    phase: train
    k: [150]
    epsilon: [1e-5]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.92579            0.77434                   25
#        0.92551            0.78522                   15
#        0.92523            0.78041                   27
#        0.92531            0.78573                   31
#        0.92554            0.78457                   25
# ------------------------------------------------------
# avg:    0.9255             0.7821
# std:    0.0002             0.0043