data:
  transductive: True
architecture:
  dim: 256
  aggr: gcn
  loss: softmax
  num_layers: 3
  act: relu
  feature_augment: none
  feature_smoothen: none
  use_label: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 35
  lr: 0.002
  dropout: 0.4
  dropedge: 0.05
  batch_size: 128
sampler:
  - method: ppr
    phase: train
    k: [150]
    epsilon: [1e-5]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.92595            0.76899                   21
#        0.92447            0.78017                   12
#        0.92564            0.77555                   19
#        0.92516            0.77405                   25
#        0.92554            0.77211                   31
# ------------------------------------------------------
# avg:    0.9254             0.7742
# std:    0.0005             0.0037