data:
  transductive: True
architecture:
  dim: 256
  aggr: gat
  heads: 4
  loss: softmax
  num_layers: 3
  act: relu
  feature_augment: none
  feature_smoothen: none
  use_label: none
  label_smoothen: none
  residue: max
  pooling: max
hyperparameter:
  end: 35
  lr: 0.001
  dropout: 0.35
  dropedge: 0.1
  batch_size: 128
sampler:
  - method: ppr
    phase: train
    k: [150]
    epsilon: [1e-5]