data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  heads: 4
  aggr: gat
  loss: softmax
  num_layers: 3
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 50
  lr: 1e-4
  dropout: 0.2
  dropedge: 0.0
  batch_size: 128
sampler:
  - method: ppr
    phase: train
    k: [200]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.97186            0.97061                   31
#        0.97190            0.97005                   31
#        0.97143            0.97061                   39
#        0.97245            0.97103                   34
#        0.97156            0.97127                   24
# ------------------------------------------------------
# avg:    0.9718             0.9707
# std:    0.0004             0.0004