data:
  to_undirected: True
  transductive: False
architecture:
  dim: 256
  aggr: gat
  heads: 4
  loss: softmax
  num_layers: 3
  act: relu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: none
  pooling: center
hyperparameter:
  end: 50
  lr: 0.0005
  dropout: 0.45
  dropedge: 0.0
  batch_size: 64
sampler:
  - method: ppr
    phase: train
    k: [200]
    threshold: [0.01]
    epsilon: [1e-6]



# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.53568            0.53870                   15
#        0.53231            0.53426                   25
#        0.53541            0.53368                   27
#        0.53254            0.53184                   15
#        0.53536            0.53610                   28
# ------------------------------------------------------
# avg:    0.5343             0.5349
# std:    0.0015             0.0023
