data:
  to_undirected: True
  transductive: True
architecture:
  dim: 256
  heads: 4
  aggr: gat
  loss: softmax
  num_layers: 5
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: max
  pooling: max
hyperparameter:
  end: 50
  lr: 1e-4
  dropout: 0.2
  dropedge: 0.0
  batch_size: 64
sampler:
  - method: ppr
    phase: train
    k: [200]
    threshold: [0.01]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.73905            0.72417                   46
#        0.73878            0.72701                   47
#        0.73885            0.72506                   39
#        0.73875            0.72436                   32
#        0.74170            0.73166                   41
# ------------------------------------------------------
# avg:    0.7394             0.7265
# std:    0.0011             0.0028