data:
  to_undirected: True
  transductive: True
architecture:
  dim: 256
  aggr: sage
  loss: softmax
  num_layers: 5
  act: elu
  use_label: none
  feature_augment: hops
  feature_smoothen: none
  label_smoothen: none
  residue: max
  pooling: max
hyperparameter:
  end: 75
  lr: 2e-5
  dropout: 0.25
  dropedge: 0.15
  batch_size: 16
sampler:
  - method: ppr
    phase: train
    k: [200]
    threshold: [0.01]
    epsilon: [1e-6]


# 5 runs:
# best valid acc      best test acc       best val epoch
#        0.73868            0.72749                   53
#        0.73747            0.72539                   52
#        0.73784            0.72526                   65
#        0.73801            0.72771                   67
#        0.73711            0.72306                   72
# ------------------------------------------------------
# avg:    0.7378             0.7258
# std:    0.0005             0.0017